FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
# Gunicorn for prod
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8001", "app:app"]