apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
spec:
  replicas: {{ .Values.replicas }}
  selector: { matchLabels: { app: api2 } }
  template:
    metadata: { labels: { app: api2 } }
    spec:
      containers:
        - name: api2
          image: {{ .Values.imageApi2 }}
          ports: [{ containerPort: 8002 }]
          env:
            - name: SERVICE_NAME
              value: {{ .Values.env.SERVICE_NAME_API2 | quote }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: client-secrets
                  key: mongodb_uri
          resources:
{{- toYaml .Values.resources | nindent 12 }}
