name: deploy-k8s
on:
  workflow_dispatch:
    inputs:
      client:
        description: "Client key (e.g., neo-retail)"
        required: true
      image_tag:
        description: "Image tag (defaults to latest)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use image tag input
        run: |
          echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          sed -i "s#:latest#:${{ env.IMAGE_TAG }}#g" clients/${{ github.event.inputs.client }}.yaml

      - name: Copy chart & client values to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "chart/*,clients/${{ github.event.inputs.client }}.yaml"
          target: "~/infra-apis/"

      - name: Run Helm on server (local kubectl)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Ensure helm & kubectl exist (install once or pre-bake on the box)
            if ! command -v helm >/dev/null; then
              curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            fi
            if ! command -v kubectl >/dev/null; then
              curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
              chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            fi

            cd ~/infra-apis
            # Use local kubeconfig (127.0.0.1 works here)
            helm upgrade --install ${{ github.event.inputs.client }} ./chart \
              --namespace ${{ secrets.K8S_NAMESPACE }} \
              --create-namespace \
              -f clients/${{ github.event.inputs.client }}.yaml
